name: Release a new version and Update Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        number: 'Version to release'
        required: true

jobs:
  release:
    name: Release ${{inputs.version}}
    runs-on: ubuntu-latest
    outputs:
      release_notes: ${{ steps.notes.outputs.RELEASE_NOTES }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        run: gh release create ${{ inputs.version }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release notes
        id: notes
        run: |
          NOTES=$(gh release view ${{ inputs.version }} --json body -q .body)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    needs: release
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update CHANGELOG.md
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ inputs.version }}
          release-notes: ${{ needs.release.outputs.release_notes }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "Update CHANGELOG for ${{ inputs.version }}"
          file_pattern: CHANGELOG.md
